#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Rparser
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     5,     3,     5,     6,     8,     9 ]

racc_action_check = [
     0,     0,     2,     1,     5,     6 ]

racc_action_pointer = [
    -2,     3,     0,   nil,   nil,     1,     5,   nil,   nil,   nil ]

racc_action_default = [
    -1,    -8,    -2,    -4,    -5,    -6,    -8,    -3,    -7,    10 ]

racc_goto_table = [
     4,     2,     7,     1 ]

racc_goto_check = [
     3,     2,     3,     1 ]

racc_goto_pointer = [
   nil,     3,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 5, :_reduce_none,
  1, 5, :_reduce_none,
  2, 6, :_reduce_3,
  1, 6, :_reduce_none,
  1, 6, :_reduce_none,
  1, 7, :_reduce_none,
  2, 7, :_reduce_7 ]

racc_reduce_n = 8

racc_shift_n = 10

racc_token_table = {
  false => 0,
  :error => 1,
  :LINE => 2,
  :NEWLINE => 3 }

racc_nt_base = 4

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LINE",
  "NEWLINE",
  "$start",
  "document",
  "lines",
  "line" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

def _reduce_3(val, _values, result)
 return val[0] + val[1] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

def _reduce_7(val, _values, result)
 return val[0] + val[1] 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Rparser
