#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

  def initialize(tokenizer)
    @tokenizer = tokenizer
    super()
  end

  def parse
    do_parse
  end

  def next_token
    @tokenizer.next_token
  end
##### State transition tables begin ###

racc_action_table = [
     4,     5,     4,     7,     8 ]

racc_action_check = [
     0,     1,     2,     4,     5 ]

racc_action_pointer = [
    -2,     1,     0,   nil,     0,     4,   nil,   nil,   nil ]

racc_action_default = [
    -6,    -6,    -1,    -3,    -4,    -6,    -2,    -5,     9 ]

racc_goto_table = [
     3,     2,     6,     1 ]

racc_goto_check = [
     3,     2,     3,     1 ]

racc_goto_pointer = [
   nil,     3,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 5, :_reduce_1,
  2, 6, :_reduce_none,
  1, 6, :_reduce_none,
  1, 7, :_reduce_none,
  2, 7, :_reduce_none ]

racc_reduce_n = 6

racc_shift_n = 9

racc_token_table = {
  false => 0,
  :error => 1,
  :LINE => 2,
  :NEWLINE => 3 }

racc_nt_base = 4

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LINE",
  "NEWLINE",
  "$start",
  "document",
  "lines",
  "line" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 puts "Z DOC #{val}" 
    result
end

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
